### PR TITLE
Move kc deployments into f8-services repo

### PR DESCRIPTION
**Pull request by hectorj2f**
related to https://github.com/fabric8io/keycloak-deployment/issues/35

ping @alexeykazakov @joshuawilson

### CODE REVIEW

**Comment by hectorj2f** [comment]
also related to https://github.com/almighty/almighty-jobs/pull/219

**Comment by joshuawilson** [comment]
@vpavlin is this the correct repo for these changes?

**Review by alexeykazakov — APPROVED** [review]
+1. @hectorj2f let us know when everything is ready to merge this PR.

**Comment by hectorj2f** [comment]
and related to https://github.com/fabric8io/fabric8-platform/pull/502

**Pull request merged**
