### PR TITLE
Separate graph imports to standalone workers

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
CC @msrb, will need changes in https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/61 and https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/62

**Comment by fridex** [comment]
Will bump worker commit hash once required changes get merged in worker repo.

**Comment by jpopelka** [comment]
@fridex  there are some conflicts

**Comment by fridex** [comment]
@jpopelka rebased.

**Comment by fridex** [comment]
Fixes:
  * CVE fixes by Jirka
  * Graph sync by Mitesh
  * separate graph importer worker

CC @msrb merge? :)

**Comment by msrb** [comment]
@vpavlin will the tooling handle this YAML?

**Comment by fridex** [comment]
> @vpavlin will the tooling handle this YAML?

saasherder is using [anymarkup](https://github.com/bkabrda/anymarkup) which uses PyYAML - this is valid YAML, but worth to double-check.

**Comment by msrb** [comment]
The image referenced by the hash failed to build in CI, so do not merge please.

**Comment by fridex** [comment]
> The image referenced by the hash failed to build in CI, so do not merge please.

Good point, haven't check it. I think we should automate these checks - opened https://github.com/openshiftio/saas/issues/211

**Comment by vpavlin** [comment]
Download of the template succeeded

**Pull request merged**
